version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: rag_llm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5477:5477"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_quiz

volumes:
  postgres_data:


networks:
  rag_quiz:
    name: rag_quiz
    external: true # use predefined network
