"""added_user_rating

Revision ID: 9914aaad2d48
Revises: 86b25b601ccf
Create Date: 2025-01-17 01:20:12.566451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9914aaad2d48'
down_revision: Union[str, None] = '86b25b601ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user_rating')
    # ### end Alembic commands ###
