"""time taken in review

Revision ID: f526606c4f89
Revises: 85f7856996db
Create Date: 2025-01-17 00:42:01.913305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f526606c4f89'
down_revision: Union[str, None] = '85f7856996db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('time_taken', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'time_taken')
    # ### end Alembic commands ###
